Feat/#3　　doPut作成
YutaNakamizo/notewebapp-backend pull request #14
Opened 2020-10-03 05:50 UTC by Tororokombu

Note　：ノートのクラス
CreateNewNote：doPutリクエストに対する応答を書いてる。

HelloAppEngine.java ,HelloAppEngineTest.java  ：仕組みを理解するために変更しただけ

サーバーの調子が悪くてデバッグできてない。
サーバーが治ったら、デバッグしてみる。。。

そんな変なことはしてないはずだから、大丈夫かと思う。。。

2020-10-03 05:53 UTC, YutaNakamizo commented
commit メッセージの "without Debug" で爆笑した.
(メッセージ日本語でいいよ)

2020-10-03 05:55 UTC, Tororokombu commented
わかった！！！

や、デバッグできんのやもん。。。

2020-10-03 05:57 UTC, YutaNakamizo commented
サーバは起動できた？
doGet メソッドがないから当然ブラウザで見に行っても何も出ないけど

2020-10-03 06:18 UTC, Tororokombu commented
再起動したら解決した！あのHelloAppEngineの方は見えるよ

2020-10-03 13:03 UTC, YutaNakamizo requested changes

2020-10-03 13:03 UTC, YutaNakamizo commented on src/main/java/Note.java
> +    private String status;
status は API の実行が成功したかを示すだけで, メモそれぞれの状態を表すわけではないです.
なので Note クラスには含めません.

```suggestion
```

2020-10-03 13:03 UTC, YutaNakamizo commented on src/main/java/Note.java
> +    private long dateCreated; //get in this class
```suggestion
    private long dateCreated; //get in this class
    private long dateLastModified;

```

2020-10-03 13:04 UTC, YutaNakamizo commented
@Tororokombu 
レビューしたので修正よろしく

2020-10-06 05:41 UTC, Tororokombu commented on src/main/java/CreateNewNote.java
> +	  request.setCharacterEncoding("Windows-31J");	//受け取るデータ型の文字系列指定
見たサイトでその指定にしろって書いてあっただけだから直す

2020-10-06 05:41 UTC, Tororokombu commented on src/main/java/CreateNewNote.java
> +      response.getWriter().println("body:"+newnote.getBody());
はい

2020-10-06 07:39 UTC, Tororokombu commented
修正したよ！！！

2020-10-08 07:28 UTC, Tororokombu commented
で、、できたよ～～～～～～（泣）

2020-10-08 12:49 UTC, YutaNakamizo commented
> で、、できたよ～～～～～～（泣）
> 
> テスト環境： Talend API Tester
> URL: http://127.0.0.1:8080/api/notes
> Header ： content type application/json
> Body ： {"title":"shopping","body":"bag,paper"}
> 
> でインスタンスの作成と、JSON形式のレスポンス確認しました。。。。

いい感じです！
(ちなみに IP アドレス 127.0.0.1 は localhost でも動きます.)

2020-10-08 12:56 UTC, YutaNakamizo approved these changes

2020-10-08 12:56 UTC, merged